version: '3.3'

services:
    api:
        image: piston_coding_web_v11
        container_name: piston_api
        restart: always
        ports:
            - 50051:50051
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /piston/jobs:exec,uid=1000,gid=1000,mode=711
            - /tmp:exec
            - /tmp/time_execute_code:exec,mode=777
